// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trixx.Cartoons.Database;

#nullable disable

namespace Trixx.Cartoons.Migrations.Migrations
{
    [DbContext(typeof(CartoonsDatabaseContext))]
    partial class CartoonsDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.CartoonSystemObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DictionaryCartoonId")
                        .HasColumnType("integer");

                    b.Property<int?>("DictionaryStudioId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryCartoonId")
                        .IsUnique();

                    b.HasIndex("DictionaryStudioId")
                        .IsUnique();

                    b.ToTable("CartoonSystemObject");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Dictionary.DictionaryCartoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativeNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedAllNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SystemObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DictionaryCartoons");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Dictionary.DictionaryCatroonStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartoonId")
                        .HasColumnType("integer");

                    b.Property<int>("DictionaryStudioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryStudioId");

                    b.HasIndex("CartoonId", "DictionaryStudioId")
                        .IsUnique();

                    b.ToTable("DictionaryCatroonStudios");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Dictionary.DictionaryStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SystemObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DictionaryStudios");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Pack.CartoonsPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SystemObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SystemObjectId");

                    b.ToTable("CartoonsPacks");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Pack.CartoonsPackLabelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartoonsPackId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("SystemObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartoonsPackId");

                    b.HasIndex("SystemObjectId");

                    b.ToTable("CartoonsPackLabelTypes");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Pack.PackCartoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartoonsPackLabelTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("DictionaryCartoonId")
                        .HasColumnType("integer");

                    b.Property<int>("SystemObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartoonsPackLabelTypeId");

                    b.HasIndex("DictionaryCartoonId");

                    b.HasIndex("SystemObjectId");

                    b.ToTable("PackCartoons");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.CartoonSystemObject", b =>
                {
                    b.HasOne("Trixx.Cartoons.Database.Models.Dictionary.DictionaryCartoon", "DictionaryCartoon")
                        .WithOne("SystemObject")
                        .HasForeignKey("Trixx.Cartoons.Database.Models.CartoonSystemObject", "DictionaryCartoonId");

                    b.HasOne("Trixx.Cartoons.Database.Models.Dictionary.DictionaryStudio", "DictionaryStudio")
                        .WithOne("SystemObject")
                        .HasForeignKey("Trixx.Cartoons.Database.Models.CartoonSystemObject", "DictionaryStudioId");

                    b.Navigation("DictionaryCartoon");

                    b.Navigation("DictionaryStudio");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Dictionary.DictionaryCatroonStudio", b =>
                {
                    b.HasOne("Trixx.Cartoons.Database.Models.Dictionary.DictionaryCartoon", "Cartoon")
                        .WithMany("Studios")
                        .HasForeignKey("CartoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trixx.Cartoons.Database.Models.Dictionary.DictionaryStudio", "DictionaryStudio")
                        .WithMany()
                        .HasForeignKey("DictionaryStudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartoon");

                    b.Navigation("DictionaryStudio");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Pack.CartoonsPack", b =>
                {
                    b.HasOne("Trixx.Cartoons.Database.Models.CartoonSystemObject", "SystemObject")
                        .WithMany()
                        .HasForeignKey("SystemObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemObject");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Pack.CartoonsPackLabelType", b =>
                {
                    b.HasOne("Trixx.Cartoons.Database.Models.Pack.CartoonsPack", "CartoonsPack")
                        .WithMany("CartoonsPackLabelTypes")
                        .HasForeignKey("CartoonsPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trixx.Cartoons.Database.Models.CartoonSystemObject", "SystemObject")
                        .WithMany()
                        .HasForeignKey("SystemObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartoonsPack");

                    b.Navigation("SystemObject");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Pack.PackCartoon", b =>
                {
                    b.HasOne("Trixx.Cartoons.Database.Models.Pack.CartoonsPackLabelType", "CartoonsPackLabelType")
                        .WithMany("PackCartoons")
                        .HasForeignKey("CartoonsPackLabelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trixx.Cartoons.Database.Models.Dictionary.DictionaryCartoon", "DictionaryCartoon")
                        .WithMany()
                        .HasForeignKey("DictionaryCartoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trixx.Cartoons.Database.Models.CartoonSystemObject", "SystemObject")
                        .WithMany()
                        .HasForeignKey("SystemObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartoonsPackLabelType");

                    b.Navigation("DictionaryCartoon");

                    b.Navigation("SystemObject");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Dictionary.DictionaryCartoon", b =>
                {
                    b.Navigation("Studios");

                    b.Navigation("SystemObject")
                        .IsRequired();
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Dictionary.DictionaryStudio", b =>
                {
                    b.Navigation("SystemObject")
                        .IsRequired();
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Pack.CartoonsPack", b =>
                {
                    b.Navigation("CartoonsPackLabelTypes");
                });

            modelBuilder.Entity("Trixx.Cartoons.Database.Models.Pack.CartoonsPackLabelType", b =>
                {
                    b.Navigation("PackCartoons");
                });
#pragma warning restore 612, 618
        }
    }
}
