<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trixx.Common\Trixx.Common.csproj" />
    <ProjectReference Include="..\Trixx.Database\Trixx.Database.csproj" />
  </ItemGroup>

</Project>
