/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAuthLoginPost } from '../fn/auth/api-auth-login-post';
import { ApiAuthLoginPost$Params } from '../fn/auth/api-auth-login-post';
import { apiAuthLoginPost$Plain } from '../fn/auth/api-auth-login-post-plain';
import { ApiAuthLoginPost$Plain$Params } from '../fn/auth/api-auth-login-post-plain';
import { apiAuthLogoutDelete } from '../fn/auth/api-auth-logout-delete';
import { ApiAuthLogoutDelete$Params } from '../fn/auth/api-auth-logout-delete';
import { apiAuthRefreshPost } from '../fn/auth/api-auth-refresh-post';
import { ApiAuthRefreshPost$Params } from '../fn/auth/api-auth-refresh-post';
import { apiAuthRefreshPost$Plain } from '../fn/auth/api-auth-refresh-post-plain';
import { ApiAuthRefreshPost$Plain$Params } from '../fn/auth/api-auth-refresh-post-plain';
import { AuthResultModel } from '../models/auth-result-model';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAuthLoginPost()` */
  static readonly ApiAuthLoginPostPath = '/api/Auth/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Plain$Response(params?: ApiAuthLoginPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResultModel>> {
    return apiAuthLoginPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Plain(params?: ApiAuthLoginPost$Plain$Params, context?: HttpContext): Observable<AuthResultModel> {

    return this.apiAuthLoginPost$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<AuthResultModel>) => r.body as AuthResultModel)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Response(params?: ApiAuthLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResultModel>> {
    return apiAuthLoginPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost(params?: ApiAuthLoginPost$Params, context?: HttpContext): Observable<AuthResultModel> {

    return this.apiAuthLoginPost$Response(params).pipe(
      map((r: StrictHttpResponse<AuthResultModel>) => r.body as AuthResultModel)
    );
  }

  /** Path part for operation `apiAuthLogoutDelete()` */
  static readonly ApiAuthLogoutDeletePath = '/api/Auth/logout';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLogoutDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthLogoutDelete$Response(params?: ApiAuthLogoutDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAuthLogoutDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLogoutDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthLogoutDelete(params?: ApiAuthLogoutDelete$Params, context?: HttpContext): Observable<void> {

    return this.apiAuthLogoutDelete$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiAuthRefreshPost()` */
  static readonly ApiAuthRefreshPostPath = '/api/Auth/refresh';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthRefreshPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthRefreshPost$Plain$Response(params?: ApiAuthRefreshPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResultModel>> {
    return apiAuthRefreshPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthRefreshPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthRefreshPost$Plain(params?: ApiAuthRefreshPost$Plain$Params, context?: HttpContext): Observable<AuthResultModel> {

    return this.apiAuthRefreshPost$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<AuthResultModel>) => r.body as AuthResultModel)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthRefreshPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthRefreshPost$Response(params?: ApiAuthRefreshPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResultModel>> {
    return apiAuthRefreshPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthRefreshPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthRefreshPost(params?: ApiAuthRefreshPost$Params, context?: HttpContext): Observable<AuthResultModel> {

    return this.apiAuthRefreshPost$Response(params).pipe(
      map((r: StrictHttpResponse<AuthResultModel>) => r.body as AuthResultModel)
    );
  }

}
