/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCartoonsFormDefaultsGet } from '../fn/cartoons/api-cartoons-form-defaults-get';
import { ApiCartoonsFormDefaultsGet$Params } from '../fn/cartoons/api-cartoons-form-defaults-get';
import { apiCartoonsFormDefaultsGet$Plain } from '../fn/cartoons/api-cartoons-form-defaults-get-plain';
import { ApiCartoonsFormDefaultsGet$Plain$Params } from '../fn/cartoons/api-cartoons-form-defaults-get-plain';
import { apiCartoonsIdDelete } from '../fn/cartoons/api-cartoons-id-delete';
import { ApiCartoonsIdDelete$Params } from '../fn/cartoons/api-cartoons-id-delete';
import { apiCartoonsIdGet } from '../fn/cartoons/api-cartoons-id-get';
import { ApiCartoonsIdGet$Params } from '../fn/cartoons/api-cartoons-id-get';
import { apiCartoonsIdGet$Plain } from '../fn/cartoons/api-cartoons-id-get-plain';
import { ApiCartoonsIdGet$Plain$Params } from '../fn/cartoons/api-cartoons-id-get-plain';
import { apiCartoonsPost } from '../fn/cartoons/api-cartoons-post';
import { ApiCartoonsPost$Params } from '../fn/cartoons/api-cartoons-post';
import { apiCartoonsSearchPost } from '../fn/cartoons/api-cartoons-search-post';
import { ApiCartoonsSearchPost$Params } from '../fn/cartoons/api-cartoons-search-post';
import { apiCartoonsSearchPost$Plain } from '../fn/cartoons/api-cartoons-search-post-plain';
import { ApiCartoonsSearchPost$Plain$Params } from '../fn/cartoons/api-cartoons-search-post-plain';
import { apiCartoonsSetFormDefaultsPost } from '../fn/cartoons/api-cartoons-set-form-defaults-post';
import { ApiCartoonsSetFormDefaultsPost$Params } from '../fn/cartoons/api-cartoons-set-form-defaults-post';
import { apiCartoonsStudiosGet } from '../fn/cartoons/api-cartoons-studios-get';
import { ApiCartoonsStudiosGet$Params } from '../fn/cartoons/api-cartoons-studios-get';
import { apiCartoonsStudiosGet$Plain } from '../fn/cartoons/api-cartoons-studios-get-plain';
import { ApiCartoonsStudiosGet$Plain$Params } from '../fn/cartoons/api-cartoons-studios-get-plain';
import { CartoonFormDefaults } from '../models/cartoon-form-defaults';
import { CartoonsListSelectItem } from '../models/cartoons-list-select-item';
import { SelectItem } from '../models/select-item';

@Injectable({ providedIn: 'root' })
export class CartoonsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCartoonsSearchPost()` */
  static readonly ApiCartoonsSearchPostPath = '/api/Cartoons/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsSearchPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsSearchPost$Plain$Response(params?: ApiCartoonsSearchPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsListSelectItem>>> {
    return apiCartoonsSearchPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsSearchPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsSearchPost$Plain(params?: ApiCartoonsSearchPost$Plain$Params, context?: HttpContext): Observable<Array<CartoonsListSelectItem>> {

    return this.apiCartoonsSearchPost$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<Array<CartoonsListSelectItem>>) => r.body as Array<CartoonsListSelectItem>)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsSearchPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsSearchPost$Response(params?: ApiCartoonsSearchPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsListSelectItem>>> {
    return apiCartoonsSearchPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsSearchPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsSearchPost(params?: ApiCartoonsSearchPost$Params, context?: HttpContext): Observable<Array<CartoonsListSelectItem>> {

    return this.apiCartoonsSearchPost$Response(params).pipe(
      map((r: StrictHttpResponse<Array<CartoonsListSelectItem>>) => r.body as Array<CartoonsListSelectItem>)
    );
  }

  /** Path part for operation `apiCartoonsIdGet()` */
  static readonly ApiCartoonsIdGetPath = '/api/Cartoons/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsIdGet$Plain$Response(params: ApiCartoonsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonsListSelectItem>> {
    return apiCartoonsIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsIdGet$Plain(params: ApiCartoonsIdGet$Plain$Params, context?: HttpContext): Observable<CartoonsListSelectItem> {

    return this.apiCartoonsIdGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<CartoonsListSelectItem>) => r.body as CartoonsListSelectItem)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsIdGet$Response(params: ApiCartoonsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonsListSelectItem>> {
    return apiCartoonsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsIdGet(params: ApiCartoonsIdGet$Params, context?: HttpContext): Observable<CartoonsListSelectItem> {

    return this.apiCartoonsIdGet$Response(params).pipe(
      map((r: StrictHttpResponse<CartoonsListSelectItem>) => r.body as CartoonsListSelectItem)
    );
  }

  /** Path part for operation `apiCartoonsIdDelete()` */
  static readonly ApiCartoonsIdDeletePath = '/api/Cartoons/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsIdDelete$Response(params: ApiCartoonsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsIdDelete(params: ApiCartoonsIdDelete$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonsIdDelete$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiCartoonsPost()` */
  static readonly ApiCartoonsPostPath = '/api/Cartoons';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsPost$Response(params?: ApiCartoonsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsPost(params?: ApiCartoonsPost$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonsPost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiCartoonsStudiosGet()` */
  static readonly ApiCartoonsStudiosGetPath = '/api/Cartoons/studios';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsStudiosGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsStudiosGet$Plain$Response(params?: ApiCartoonsStudiosGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SelectItem>>> {
    return apiCartoonsStudiosGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsStudiosGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsStudiosGet$Plain(params?: ApiCartoonsStudiosGet$Plain$Params, context?: HttpContext): Observable<Array<SelectItem>> {

    return this.apiCartoonsStudiosGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<Array<SelectItem>>) => r.body as Array<SelectItem>)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsStudiosGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsStudiosGet$Response(params?: ApiCartoonsStudiosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SelectItem>>> {
    return apiCartoonsStudiosGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsStudiosGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsStudiosGet(params?: ApiCartoonsStudiosGet$Params, context?: HttpContext): Observable<Array<SelectItem>> {

    return this.apiCartoonsStudiosGet$Response(params).pipe(
      map((r: StrictHttpResponse<Array<SelectItem>>) => r.body as Array<SelectItem>)
    );
  }

  /** Path part for operation `apiCartoonsFormDefaultsGet()` */
  static readonly ApiCartoonsFormDefaultsGetPath = '/api/Cartoons/form-defaults';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsFormDefaultsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsFormDefaultsGet$Plain$Response(params?: ApiCartoonsFormDefaultsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonFormDefaults>> {
    return apiCartoonsFormDefaultsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsFormDefaultsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsFormDefaultsGet$Plain(params?: ApiCartoonsFormDefaultsGet$Plain$Params, context?: HttpContext): Observable<CartoonFormDefaults> {

    return this.apiCartoonsFormDefaultsGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<CartoonFormDefaults>) => r.body as CartoonFormDefaults)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsFormDefaultsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsFormDefaultsGet$Response(params?: ApiCartoonsFormDefaultsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonFormDefaults>> {
    return apiCartoonsFormDefaultsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsFormDefaultsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsFormDefaultsGet(params?: ApiCartoonsFormDefaultsGet$Params, context?: HttpContext): Observable<CartoonFormDefaults> {

    return this.apiCartoonsFormDefaultsGet$Response(params).pipe(
      map((r: StrictHttpResponse<CartoonFormDefaults>) => r.body as CartoonFormDefaults)
    );
  }

  /** Path part for operation `apiCartoonsSetFormDefaultsPost()` */
  static readonly ApiCartoonsSetFormDefaultsPostPath = '/api/Cartoons/set-form-defaults';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsSetFormDefaultsPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsSetFormDefaultsPost$Response(params?: ApiCartoonsSetFormDefaultsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonsSetFormDefaultsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsSetFormDefaultsPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsSetFormDefaultsPost(params?: ApiCartoonsSetFormDefaultsPost$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonsSetFormDefaultsPost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

}
