/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCartoonsGet } from '../fn/cartoons/api-cartoons-get';
import { ApiCartoonsGet$Params } from '../fn/cartoons/api-cartoons-get';
import { apiCartoonsGet$Plain } from '../fn/cartoons/api-cartoons-get-plain';
import { ApiCartoonsGet$Plain$Params } from '../fn/cartoons/api-cartoons-get-plain';
import { apiCartoonsIdDelete } from '../fn/cartoons/api-cartoons-id-delete';
import { ApiCartoonsIdDelete$Params } from '../fn/cartoons/api-cartoons-id-delete';
import { apiCartoonsPost } from '../fn/cartoons/api-cartoons-post';
import { ApiCartoonsPost$Params } from '../fn/cartoons/api-cartoons-post';
import { CartoonsListSelectItem } from '../models/cartoons-list-select-item';

@Injectable({ providedIn: 'root' })
export class CartoonsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCartoonsGet()` */
  static readonly ApiCartoonsGetPath = '/api/Cartoons';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsGet$Plain$Response(params?: ApiCartoonsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsListSelectItem>>> {
    return apiCartoonsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsGet$Plain(params?: ApiCartoonsGet$Plain$Params, context?: HttpContext): Observable<Array<CartoonsListSelectItem>> {

    return this.apiCartoonsGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<Array<CartoonsListSelectItem>>) => r.body as Array<CartoonsListSelectItem>)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsGet$Response(params?: ApiCartoonsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsListSelectItem>>> {
    return apiCartoonsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsGet(params?: ApiCartoonsGet$Params, context?: HttpContext): Observable<Array<CartoonsListSelectItem>> {

    return this.apiCartoonsGet$Response(params).pipe(
      map((r: StrictHttpResponse<Array<CartoonsListSelectItem>>) => r.body as Array<CartoonsListSelectItem>)
    );
  }

  /** Path part for operation `apiCartoonsPost()` */
  static readonly ApiCartoonsPostPath = '/api/Cartoons';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsPost$Response(params?: ApiCartoonsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonsPost(params?: ApiCartoonsPost$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonsPost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiCartoonsIdDelete()` */
  static readonly ApiCartoonsIdDeletePath = '/api/Cartoons/id';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsIdDelete$Response(params?: ApiCartoonsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonsIdDelete(params?: ApiCartoonsIdDelete$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonsIdDelete$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

}
