/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCartoonPackCardIdGet } from '../fn/cartoon-pack/api-cartoon-pack-card-id-get';
import { ApiCartoonPackCardIdGet$Params } from '../fn/cartoon-pack/api-cartoon-pack-card-id-get';
import { apiCartoonPackCardIdGet$Plain } from '../fn/cartoon-pack/api-cartoon-pack-card-id-get-plain';
import { ApiCartoonPackCardIdGet$Plain$Params } from '../fn/cartoon-pack/api-cartoon-pack-card-id-get-plain';
import { apiCartoonPackDeleteLabelTypeIdDelete } from '../fn/cartoon-pack/api-cartoon-pack-delete-label-type-id-delete';
import { ApiCartoonPackDeleteLabelTypeIdDelete$Params } from '../fn/cartoon-pack/api-cartoon-pack-delete-label-type-id-delete';
import { apiCartoonPackEditCartoonsPackPost } from '../fn/cartoon-pack/api-cartoon-pack-edit-cartoons-pack-post';
import { ApiCartoonPackEditCartoonsPackPost$Params } from '../fn/cartoon-pack/api-cartoon-pack-edit-cartoons-pack-post';
import { apiCartoonPackEditLabelTypePost } from '../fn/cartoon-pack/api-cartoon-pack-edit-label-type-post';
import { ApiCartoonPackEditLabelTypePost$Params } from '../fn/cartoon-pack/api-cartoon-pack-edit-label-type-post';
import { apiCartoonPackGet } from '../fn/cartoon-pack/api-cartoon-pack-get';
import { ApiCartoonPackGet$Params } from '../fn/cartoon-pack/api-cartoon-pack-get';
import { apiCartoonPackGet$Plain } from '../fn/cartoon-pack/api-cartoon-pack-get-plain';
import { ApiCartoonPackGet$Plain$Params } from '../fn/cartoon-pack/api-cartoon-pack-get-plain';
import { apiCartoonPackIdGet } from '../fn/cartoon-pack/api-cartoon-pack-id-get';
import { ApiCartoonPackIdGet$Params } from '../fn/cartoon-pack/api-cartoon-pack-id-get';
import { apiCartoonPackIdGet$Plain } from '../fn/cartoon-pack/api-cartoon-pack-id-get-plain';
import { ApiCartoonPackIdGet$Plain$Params } from '../fn/cartoon-pack/api-cartoon-pack-id-get-plain';
import { apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost } from '../fn/cartoon-pack/api-cartoon-pack-replace-cartoon-pack-id-label-type-id-dictionary-cartoon-id-post';
import { ApiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost$Params } from '../fn/cartoon-pack/api-cartoon-pack-replace-cartoon-pack-id-label-type-id-dictionary-cartoon-id-post';
import { CartoonsPackListItem } from '../models/cartoons-pack-list-item';
import { CartoonsPackModel } from '../models/cartoons-pack-model';
import { SelectItem } from '../models/select-item';

@Injectable({ providedIn: 'root' })
export class CartoonPackService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCartoonPackGet()` */
  static readonly ApiCartoonPackGetPath = '/api/CartoonPack';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackGet$Plain$Response(params?: ApiCartoonPackGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsPackListItem>>> {
    return apiCartoonPackGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackGet$Plain(params?: ApiCartoonPackGet$Plain$Params, context?: HttpContext): Observable<Array<CartoonsPackListItem>> {

    return this.apiCartoonPackGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<Array<CartoonsPackListItem>>) => r.body as Array<CartoonsPackListItem>)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackGet$Response(params?: ApiCartoonPackGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsPackListItem>>> {
    return apiCartoonPackGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackGet(params?: ApiCartoonPackGet$Params, context?: HttpContext): Observable<Array<CartoonsPackListItem>> {

    return this.apiCartoonPackGet$Response(params).pipe(
      map((r: StrictHttpResponse<Array<CartoonsPackListItem>>) => r.body as Array<CartoonsPackListItem>)
    );
  }

  /** Path part for operation `apiCartoonPackIdGet()` */
  static readonly ApiCartoonPackIdGetPath = '/api/CartoonPack/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackIdGet$Plain$Response(params: ApiCartoonPackIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SelectItem>> {
    return apiCartoonPackIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackIdGet$Plain(params: ApiCartoonPackIdGet$Plain$Params, context?: HttpContext): Observable<SelectItem> {

    return this.apiCartoonPackIdGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<SelectItem>) => r.body as SelectItem)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackIdGet$Response(params: ApiCartoonPackIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SelectItem>> {
    return apiCartoonPackIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackIdGet(params: ApiCartoonPackIdGet$Params, context?: HttpContext): Observable<SelectItem> {

    return this.apiCartoonPackIdGet$Response(params).pipe(
      map((r: StrictHttpResponse<SelectItem>) => r.body as SelectItem)
    );
  }

  /** Path part for operation `apiCartoonPackCardIdGet()` */
  static readonly ApiCartoonPackCardIdGetPath = '/api/CartoonPack/card/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackCardIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackCardIdGet$Plain$Response(params: ApiCartoonPackCardIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonsPackModel>> {
    return apiCartoonPackCardIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackCardIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackCardIdGet$Plain(params: ApiCartoonPackCardIdGet$Plain$Params, context?: HttpContext): Observable<CartoonsPackModel> {

    return this.apiCartoonPackCardIdGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<CartoonsPackModel>) => r.body as CartoonsPackModel)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackCardIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackCardIdGet$Response(params: ApiCartoonPackCardIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonsPackModel>> {
    return apiCartoonPackCardIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackCardIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackCardIdGet(params: ApiCartoonPackCardIdGet$Params, context?: HttpContext): Observable<CartoonsPackModel> {

    return this.apiCartoonPackCardIdGet$Response(params).pipe(
      map((r: StrictHttpResponse<CartoonsPackModel>) => r.body as CartoonsPackModel)
    );
  }

  /** Path part for operation `apiCartoonPackEditCartoonsPackPost()` */
  static readonly ApiCartoonPackEditCartoonsPackPostPath = '/api/CartoonPack/edit-cartoons-pack';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackEditCartoonsPackPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonPackEditCartoonsPackPost$Response(params?: ApiCartoonPackEditCartoonsPackPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonPackEditCartoonsPackPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackEditCartoonsPackPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonPackEditCartoonsPackPost(params?: ApiCartoonPackEditCartoonsPackPost$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonPackEditCartoonsPackPost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiCartoonPackEditLabelTypePost()` */
  static readonly ApiCartoonPackEditLabelTypePostPath = '/api/CartoonPack/edit-label-type';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackEditLabelTypePost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonPackEditLabelTypePost$Response(params?: ApiCartoonPackEditLabelTypePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonPackEditLabelTypePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackEditLabelTypePost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCartoonPackEditLabelTypePost(params?: ApiCartoonPackEditLabelTypePost$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonPackEditLabelTypePost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiCartoonPackDeleteLabelTypeIdDelete()` */
  static readonly ApiCartoonPackDeleteLabelTypeIdDeletePath = '/api/CartoonPack/delete-label-type/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackDeleteLabelTypeIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackDeleteLabelTypeIdDelete$Response(params: ApiCartoonPackDeleteLabelTypeIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonPackDeleteLabelTypeIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackDeleteLabelTypeIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackDeleteLabelTypeIdDelete(params: ApiCartoonPackDeleteLabelTypeIdDelete$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonPackDeleteLabelTypeIdDelete$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost()` */
  static readonly ApiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPostPath = '/api/CartoonPack/replace-cartoon/{packId}/{labelTypeId}/{dictionaryCartoonId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost$Response(params: ApiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost(params: ApiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost$Params, context?: HttpContext): Observable<void> {

    return this.apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

}
