/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiMainPageGet } from '../fn/main-page/api-main-page-get';
import { ApiMainPageGet$Params } from '../fn/main-page/api-main-page-get';
import { apiMainPageGet$Plain } from '../fn/main-page/api-main-page-get-plain';
import { ApiMainPageGet$Plain$Params } from '../fn/main-page/api-main-page-get-plain';

@Injectable({ providedIn: 'root' })
export class MainPageService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiMainPageGet()` */
  static readonly ApiMainPageGetPath = '/api/MainPage';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMainPageGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMainPageGet$Plain$Response(params?: ApiMainPageGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return apiMainPageGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMainPageGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMainPageGet$Plain(params?: ApiMainPageGet$Plain$Params, context?: HttpContext): Observable<string> {

    return this.apiMainPageGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<string>) => r.body as string)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMainPageGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMainPageGet$Response(params?: ApiMainPageGet$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return apiMainPageGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMainPageGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMainPageGet(params?: ApiMainPageGet$Params, context?: HttpContext): Observable<string> {

    return this.apiMainPageGet$Response(params).pipe(
      map((r: StrictHttpResponse<string>) => r.body as string)
    );
  }

}
