/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiRolesEditRolePost } from '../fn/roles/api-roles-edit-role-post';
import { ApiRolesEditRolePost$Params } from '../fn/roles/api-roles-edit-role-post';
import { apiRolesIdGet } from '../fn/roles/api-roles-id-get';
import { ApiRolesIdGet$Params } from '../fn/roles/api-roles-id-get';
import { apiRolesIdGet$Plain } from '../fn/roles/api-roles-id-get-plain';
import { ApiRolesIdGet$Plain$Params } from '../fn/roles/api-roles-id-get-plain';
import { apiRolesRolesGet } from '../fn/roles/api-roles-roles-get';
import { ApiRolesRolesGet$Params } from '../fn/roles/api-roles-roles-get';
import { apiRolesRolesGet$Plain } from '../fn/roles/api-roles-roles-get-plain';
import { ApiRolesRolesGet$Plain$Params } from '../fn/roles/api-roles-roles-get-plain';
import { RoleListItem } from '../models/role-list-item';
import { RoleModel } from '../models/role-model';

@Injectable({ providedIn: 'root' })
export class RolesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiRolesEditRolePost()` */
  static readonly ApiRolesEditRolePostPath = '/api/Roles/edit-role';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesEditRolePost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolesEditRolePost$Response(params?: ApiRolesEditRolePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiRolesEditRolePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesEditRolePost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolesEditRolePost(params?: ApiRolesEditRolePost$Params, context?: HttpContext): Observable<void> {

    return this.apiRolesEditRolePost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiRolesRolesGet()` */
  static readonly ApiRolesRolesGetPath = '/api/Roles/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesRolesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesRolesGet$Plain$Response(params?: ApiRolesRolesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleListItem>>> {
    return apiRolesRolesGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesRolesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesRolesGet$Plain(params?: ApiRolesRolesGet$Plain$Params, context?: HttpContext): Observable<Array<RoleListItem>> {

    return this.apiRolesRolesGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<Array<RoleListItem>>) => r.body as Array<RoleListItem>)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesRolesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesRolesGet$Response(params?: ApiRolesRolesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleListItem>>> {
    return apiRolesRolesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesRolesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesRolesGet(params?: ApiRolesRolesGet$Params, context?: HttpContext): Observable<Array<RoleListItem>> {

    return this.apiRolesRolesGet$Response(params).pipe(
      map((r: StrictHttpResponse<Array<RoleListItem>>) => r.body as Array<RoleListItem>)
    );
  }

  /** Path part for operation `apiRolesIdGet()` */
  static readonly ApiRolesIdGetPath = '/api/Roles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesIdGet$Plain$Response(params: ApiRolesIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleModel>> {
    return apiRolesIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesIdGet$Plain(params: ApiRolesIdGet$Plain$Params, context?: HttpContext): Observable<RoleModel> {

    return this.apiRolesIdGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<RoleModel>) => r.body as RoleModel)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesIdGet$Response(params: ApiRolesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleModel>> {
    return apiRolesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesIdGet(params: ApiRolesIdGet$Params, context?: HttpContext): Observable<RoleModel> {

    return this.apiRolesIdGet$Response(params).pipe(
      map((r: StrictHttpResponse<RoleModel>) => r.body as RoleModel)
    );
  }

}
