/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiStudiosGet } from '../fn/studios/api-studios-get';
import { ApiStudiosGet$Params } from '../fn/studios/api-studios-get';
import { apiStudiosGet$Plain } from '../fn/studios/api-studios-get-plain';
import { ApiStudiosGet$Plain$Params } from '../fn/studios/api-studios-get-plain';
import { apiStudiosIdDelete } from '../fn/studios/api-studios-id-delete';
import { ApiStudiosIdDelete$Params } from '../fn/studios/api-studios-id-delete';
import { apiStudiosIdGet } from '../fn/studios/api-studios-id-get';
import { ApiStudiosIdGet$Params } from '../fn/studios/api-studios-id-get';
import { apiStudiosIdGet$Plain } from '../fn/studios/api-studios-id-get-plain';
import { ApiStudiosIdGet$Plain$Params } from '../fn/studios/api-studios-id-get-plain';
import { apiStudiosPost } from '../fn/studios/api-studios-post';
import { ApiStudiosPost$Params } from '../fn/studios/api-studios-post';
import { StudiosListSelectItem } from '../models/studios-list-select-item';

@Injectable({ providedIn: 'root' })
export class StudiosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiStudiosGet()` */
  static readonly ApiStudiosGetPath = '/api/Studios';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudiosGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosGet$Plain$Response(params?: ApiStudiosGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudiosListSelectItem>>> {
    return apiStudiosGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudiosGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosGet$Plain(params?: ApiStudiosGet$Plain$Params, context?: HttpContext): Observable<Array<StudiosListSelectItem>> {

    return this.apiStudiosGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<Array<StudiosListSelectItem>>) => r.body as Array<StudiosListSelectItem>)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudiosGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosGet$Response(params?: ApiStudiosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudiosListSelectItem>>> {
    return apiStudiosGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudiosGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosGet(params?: ApiStudiosGet$Params, context?: HttpContext): Observable<Array<StudiosListSelectItem>> {

    return this.apiStudiosGet$Response(params).pipe(
      map((r: StrictHttpResponse<Array<StudiosListSelectItem>>) => r.body as Array<StudiosListSelectItem>)
    );
  }

  /** Path part for operation `apiStudiosPost()` */
  static readonly ApiStudiosPostPath = '/api/Studios';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudiosPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudiosPost$Response(params?: ApiStudiosPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiStudiosPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudiosPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudiosPost(params?: ApiStudiosPost$Params, context?: HttpContext): Observable<void> {

    return this.apiStudiosPost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiStudiosIdGet()` */
  static readonly ApiStudiosIdGetPath = '/api/Studios/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudiosIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosIdGet$Plain$Response(params: ApiStudiosIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<StudiosListSelectItem>> {
    return apiStudiosIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudiosIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosIdGet$Plain(params: ApiStudiosIdGet$Plain$Params, context?: HttpContext): Observable<StudiosListSelectItem> {

    return this.apiStudiosIdGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<StudiosListSelectItem>) => r.body as StudiosListSelectItem)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudiosIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosIdGet$Response(params: ApiStudiosIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<StudiosListSelectItem>> {
    return apiStudiosIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudiosIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosIdGet(params: ApiStudiosIdGet$Params, context?: HttpContext): Observable<StudiosListSelectItem> {

    return this.apiStudiosIdGet$Response(params).pipe(
      map((r: StrictHttpResponse<StudiosListSelectItem>) => r.body as StudiosListSelectItem)
    );
  }

  /** Path part for operation `apiStudiosIdDelete()` */
  static readonly ApiStudiosIdDeletePath = '/api/Studios/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudiosIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosIdDelete$Response(params: ApiStudiosIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiStudiosIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudiosIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudiosIdDelete(params: ApiStudiosIdDelete$Params, context?: HttpContext): Observable<void> {

    return this.apiStudiosIdDelete$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

}
