/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUsersChangeUserLockStatusUserIdPost } from '../fn/users/api-users-change-user-lock-status-user-id-post';
import { ApiUsersChangeUserLockStatusUserIdPost$Params } from '../fn/users/api-users-change-user-lock-status-user-id-post';
import { apiUsersCreateUserManuallyPost } from '../fn/users/api-users-create-user-manually-post';
import { ApiUsersCreateUserManuallyPost$Params } from '../fn/users/api-users-create-user-manually-post';
import { apiUsersIdGet } from '../fn/users/api-users-id-get';
import { ApiUsersIdGet$Params } from '../fn/users/api-users-id-get';
import { apiUsersIdGet$Plain } from '../fn/users/api-users-id-get-plain';
import { ApiUsersIdGet$Plain$Params } from '../fn/users/api-users-id-get-plain';
import { apiUsersUsersGet } from '../fn/users/api-users-users-get';
import { ApiUsersUsersGet$Params } from '../fn/users/api-users-users-get';
import { apiUsersUsersGet$Plain } from '../fn/users/api-users-users-get-plain';
import { ApiUsersUsersGet$Plain$Params } from '../fn/users/api-users-users-get-plain';
import { UserListItem } from '../models/user-list-item';
import { UserModel } from '../models/user-model';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUsersCreateUserManuallyPost()` */
  static readonly ApiUsersCreateUserManuallyPostPath = '/api/Users/create-user-manually';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersCreateUserManuallyPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersCreateUserManuallyPost$Response(params?: ApiUsersCreateUserManuallyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUsersCreateUserManuallyPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersCreateUserManuallyPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersCreateUserManuallyPost(params?: ApiUsersCreateUserManuallyPost$Params, context?: HttpContext): Observable<void> {

    return this.apiUsersCreateUserManuallyPost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

  /** Path part for operation `apiUsersUsersGet()` */
  static readonly ApiUsersUsersGetPath = '/api/Users/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersUsersGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersUsersGet$Plain$Response(params?: ApiUsersUsersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserListItem>>> {
    return apiUsersUsersGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersUsersGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersUsersGet$Plain(params?: ApiUsersUsersGet$Plain$Params, context?: HttpContext): Observable<Array<UserListItem>> {

    return this.apiUsersUsersGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<Array<UserListItem>>) => r.body as Array<UserListItem>)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersUsersGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersUsersGet$Response(params?: ApiUsersUsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserListItem>>> {
    return apiUsersUsersGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersUsersGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersUsersGet(params?: ApiUsersUsersGet$Params, context?: HttpContext): Observable<Array<UserListItem>> {

    return this.apiUsersUsersGet$Response(params).pipe(
      map((r: StrictHttpResponse<Array<UserListItem>>) => r.body as Array<UserListItem>)
    );
  }

  /** Path part for operation `apiUsersIdGet()` */
  static readonly ApiUsersIdGetPath = '/api/Users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersIdGet$Plain$Response(params: ApiUsersIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserModel>> {
    return apiUsersIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersIdGet$Plain(params: ApiUsersIdGet$Plain$Params, context?: HttpContext): Observable<UserModel> {

    return this.apiUsersIdGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<UserModel>) => r.body as UserModel)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersIdGet$Response(params: ApiUsersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserModel>> {
    return apiUsersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersIdGet(params: ApiUsersIdGet$Params, context?: HttpContext): Observable<UserModel> {

    return this.apiUsersIdGet$Response(params).pipe(
      map((r: StrictHttpResponse<UserModel>) => r.body as UserModel)
    );
  }

  /** Path part for operation `apiUsersChangeUserLockStatusUserIdPost()` */
  static readonly ApiUsersChangeUserLockStatusUserIdPostPath = '/api/Users/change-user-lock-status/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersChangeUserLockStatusUserIdPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersChangeUserLockStatusUserIdPost$Response(params: ApiUsersChangeUserLockStatusUserIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUsersChangeUserLockStatusUserIdPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersChangeUserLockStatusUserIdPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersChangeUserLockStatusUserIdPost(params: ApiUsersChangeUserLockStatusUserIdPost$Params, context?: HttpContext): Observable<void> {

    return this.apiUsersChangeUserLockStatusUserIdPost$Response(params).pipe(
      map((r: StrictHttpResponse<void>) => r.body as void)
    );
  }

}
