/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUserProfileGet } from '../fn/user-profile/api-user-profile-get';
import { ApiUserProfileGet$Params } from '../fn/user-profile/api-user-profile-get';
import { apiUserProfileGet$Plain } from '../fn/user-profile/api-user-profile-get-plain';
import { ApiUserProfileGet$Plain$Params } from '../fn/user-profile/api-user-profile-get-plain';
import { UserProfileModel } from '../models/user-profile-model';

@Injectable({ providedIn: 'root' })
export class UserProfileService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUserProfileGet()` */
  static readonly ApiUserProfileGetPath = '/api/UserProfile';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserProfileGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserProfileGet$Plain$Response(params?: ApiUserProfileGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfileModel>> {
    return apiUserProfileGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserProfileGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserProfileGet$Plain(params?: ApiUserProfileGet$Plain$Params, context?: HttpContext): Observable<UserProfileModel> {

    return this.apiUserProfileGet$Plain$Response(params).pipe(
      map((r: StrictHttpResponse<UserProfileModel>) => r.body as UserProfileModel)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserProfileGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserProfileGet$Response(params?: ApiUserProfileGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfileModel>> {
    return apiUserProfileGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserProfileGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserProfileGet(params?: ApiUserProfileGet$Params, context?: HttpContext): Observable<UserProfileModel> {

    return this.apiUserProfileGet$Response(params).pipe(
      map((r: StrictHttpResponse<UserProfileModel>) => r.body as UserProfileModel)
    );
  }

}
