/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost$Params {
  packId: number;
  labelTypeId: number;
  dictionaryCartoonId: number;
}

export function apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost(http: HttpClient, rootUrl: string, params: ApiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost.PATH, 'post');
  if (params) {
    rb.path('packId', params.packId, {"style":"simple"});
    rb.path('labelTypeId', params.labelTypeId, {"style":"simple"});
    rb.path('dictionaryCartoonId', params.dictionaryCartoonId, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiCartoonPackReplaceCartoonPackIdLabelTypeIdDictionaryCartoonIdPost.PATH = '/api/CartoonPack/replace-cartoon/{packId}/{labelTypeId}/{dictionaryCartoonId}';
