/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartoonsPackListItem } from '../../models/cartoons-pack-list-item';

export interface ApiCartoonPackGet$Params {
}

export function apiCartoonPackGet(http: HttpClient, rootUrl: string, params?: ApiCartoonPackGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsPackListItem>>> {
  const rb = new RequestBuilder(rootUrl, apiCartoonPackGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CartoonsPackListItem>>;
    })
  );
}

apiCartoonPackGet.PATH = '/api/CartoonPack';
