/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SelectItem } from '../../models/select-item';

export interface ApiCartoonPackIdGet$Plain$Params {
  id: number;
}

export function apiCartoonPackIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCartoonPackIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SelectItem>> {
  const rb = new RequestBuilder(rootUrl, apiCartoonPackIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SelectItem>;
    })
  );
}

apiCartoonPackIdGet$Plain.PATH = '/api/CartoonPack/{id}';
