/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartoonsPackModel } from '../../models/cartoons-pack-model';

export interface ApiCartoonPackCardIdGet$Params {
  id: number;
}

export function apiCartoonPackCardIdGet(http: HttpClient, rootUrl: string, params: ApiCartoonPackCardIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonsPackModel>> {
  const rb = new RequestBuilder(rootUrl, apiCartoonPackCardIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartoonsPackModel>;
    })
  );
}

apiCartoonPackCardIdGet.PATH = '/api/CartoonPack/card/{id}';
