/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SelectItem } from '../../models/select-item';

export interface ApiUsersRolesPost$Params {
}

export function apiUsersRolesPost(http: HttpClient, rootUrl: string, params?: ApiUsersRolesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SelectItem>>> {
  const rb = new RequestBuilder(rootUrl, apiUsersRolesPost.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SelectItem>>;
    })
  );
}

apiUsersRolesPost.PATH = '/api/Users/roles';
