/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiUsersChangeUserLockStatusUserIdPost$Params {
  userId: number;
  toLock?: boolean;
}

export function apiUsersChangeUserLockStatusUserIdPost(http: HttpClient, rootUrl: string, params: ApiUsersChangeUserLockStatusUserIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiUsersChangeUserLockStatusUserIdPost.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {"style":"simple"});
    rb.query('toLock', params.toLock, {"style":"form"});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiUsersChangeUserLockStatusUserIdPost.PATH = '/api/Users/change-user-lock-status/{userId}';
