/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudiosListSelectItem } from '../../models/studios-list-select-item';

export interface ApiStudiosGet$Params {
}

export function apiStudiosGet(http: HttpClient, rootUrl: string, params?: ApiStudiosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudiosListSelectItem>>> {
  const rb = new RequestBuilder(rootUrl, apiStudiosGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StudiosListSelectItem>>;
    })
  );
}

apiStudiosGet.PATH = '/api/Studios';
