/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserProfileModel } from '../../models/user-profile-model';

export interface ApiUserProfileGet$Plain$Params {
}

export function apiUserProfileGet$Plain(http: HttpClient, rootUrl: string, params?: ApiUserProfileGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfileModel>> {
  const rb = new RequestBuilder(rootUrl, apiUserProfileGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserProfileModel>;
    })
  );
}

apiUserProfileGet$Plain.PATH = '/api/UserProfile';
