/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthRequestModel } from '../../models/auth-request-model';
import { AuthResultModel } from '../../models/auth-result-model';

export interface ApiAuthLoginPost$Params {
      body?: AuthRequestModel
}

export function apiAuthLoginPost(http: HttpClient, rootUrl: string, params?: ApiAuthLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResultModel>> {
  const rb = new RequestBuilder(rootUrl, apiAuthLoginPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthResultModel>;
    })
  );
}

apiAuthLoginPost.PATH = '/api/Auth/login';
