/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthResultModel } from '../../models/auth-result-model';

export interface ApiAuthRefreshPost$Plain$Params {
  userId?: number;
  refreshToken?: string;
}

export function apiAuthRefreshPost$Plain(http: HttpClient, rootUrl: string, params?: ApiAuthRefreshPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResultModel>> {
  const rb = new RequestBuilder(rootUrl, apiAuthRefreshPost$Plain.PATH, 'post');
  if (params) {
    rb.query('userId', params.userId, {"style":"form"});
    rb.query('refreshToken', params.refreshToken, {"style":"form"});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthResultModel>;
    })
  );
}

apiAuthRefreshPost$Plain.PATH = '/api/Auth/refresh';
