/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartoonFormDefaults } from '../../models/cartoon-form-defaults';

export interface ApiCartoonsFormDefaultsGet$Params {
}

export function apiCartoonsFormDefaultsGet(http: HttpClient, rootUrl: string, params?: ApiCartoonsFormDefaultsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonFormDefaults>> {
  const rb = new RequestBuilder(rootUrl, apiCartoonsFormDefaultsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartoonFormDefaults>;
    })
  );
}

apiCartoonsFormDefaultsGet.PATH = '/api/Cartoons/form-defaults';
