/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartoonsListSelectItem } from '../../models/cartoons-list-select-item';

export interface ApiCartoonsGet$Params {
}

export function apiCartoonsGet(http: HttpClient, rootUrl: string, params?: ApiCartoonsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsListSelectItem>>> {
  const rb = new RequestBuilder(rootUrl, apiCartoonsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CartoonsListSelectItem>>;
    })
  );
}

apiCartoonsGet.PATH = '/api/Cartoons';
