/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartoonsFilterModel } from '../../models/cartoons-filter-model';
import { CartoonsListSelectItem } from '../../models/cartoons-list-select-item';

export interface ApiCartoonsSearchPost$Params {
      body?: CartoonsFilterModel
}

export function apiCartoonsSearchPost(http: HttpClient, rootUrl: string, params?: ApiCartoonsSearchPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartoonsListSelectItem>>> {
  const rb = new RequestBuilder(rootUrl, apiCartoonsSearchPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CartoonsListSelectItem>>;
    })
  );
}

apiCartoonsSearchPost.PATH = '/api/Cartoons/search';
