/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartoonsListSelectItem } from '../../models/cartoons-list-select-item';

export interface ApiCartoonsIdGet$Params {
  id: number;
}

export function apiCartoonsIdGet(http: HttpClient, rootUrl: string, params: ApiCartoonsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CartoonsListSelectItem>> {
  const rb = new RequestBuilder(rootUrl, apiCartoonsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartoonsListSelectItem>;
    })
  );
}

apiCartoonsIdGet.PATH = '/api/Cartoons/{id}';
