/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelType } from '../models/label-type';
export interface CartoonsPackModel {
  labelTypes: Array<LabelType>;
  name: string;
}
