/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RefItem } from '../models/ref-item';
import { SelectItem } from '../models/select-item';
export interface CartoonsListSelectItem {
  alternativeNames?: Array<string> | null;
  id: number;
  label?: string | null;
  sources?: Array<RefItem> | null;
  studios?: Array<SelectItem> | null;
  type?: string | null;
  year?: number | null;
}
