/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartoonType } from '../models/cartoon-type';
export interface CartoonUpdateModel {
  alternativeNames?: Array<string> | null;
  id?: number | null;
  name?: string | null;
  sources?: Array<string> | null;
  studios?: Array<number> | null;
  type?: CartoonType;
  year?: number | null;
}
