/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartoonType } from '../models/cartoon-type';
export interface CartoonItem {
  alternativeNames: string;
  cartoonType?: CartoonType;
  dictionaryCartoonId: number;
  name: string;
  year?: number | null;
}
