/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartoonsListSelectItem {
  alternativeNames?: Array<string> | null;
  id?: number;
  label?: string | null;
  sources?: Array<string> | null;
  studios?: Array<string> | null;
  year?: number;
}
