/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SelectItem } from '../models/select-item';
export interface CartoonUpdateModel {
  alternativeNames?: Array<string> | null;
  id?: number | null;
  name?: string | null;
  sources?: Array<string> | null;
  studios?: Array<SelectItem> | null;
  year?: number;
}
