/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum CartoonType {
  FeatureLengthFilm = '\u043F/\u043C',
  ShortFilm = '\u043A/\u043C',
  SerialFilm = '\u043C/\u0441'
}
