/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartoonUpdateModel {
  alternativeNames?: Array<string> | null;
  id?: number | null;
  name?: string | null;
  sources?: Array<string> | null;
  studios?: Array<number> | null;
  year?: number | null;
}
