/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartoonsPackLabelTypeEditModel {
  cartoonPackId?: number;
  id?: number | null;
  name?: string | null;
  order?: number;
}
