/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum CommonPermission {
  Read = '\u0427\u0442\u0435\u043D\u0438\u0435',
  Edit = '\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435',
  Delete = '\u0423\u0434\u0430\u043B\u0435\u043D\u0438\u0435'
}
