/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartoonItem } from '../models/cartoon-item';
export interface LabelType {
  cartoons: Array<CartoonItem>;
  id: number;
  name?: string | null;
  order: number;
}
