/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum Permission {
  MainPageRead = 'MainPage_Read',
  DictionaryCartoonsRead = 'DictionaryCartoons_Read',
  DictionaryCartoonsEdit = 'DictionaryCartoons_Edit',
  DictionaryCartoonsDelete = 'DictionaryCartoons_Delete',
  DictionaryStudiosRead = 'DictionaryStudios_Read',
  DictionaryStudiosEdit = 'DictionaryStudios_Edit',
  DictionaryStudiosDelete = 'DictionaryStudios_Delete'
}
