/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommonPermission } from '../models/common-permission';
import { Permission } from '../models/permission';
export interface PermissionModel {
  commonPermission: CommonPermission;
  id?: Permission;
  isGranted?: boolean | null;
}
