/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum Permission {
  MainPage_Read = 'MainPage_Read',
  DictionaryCartoons_Read = 'DictionaryCartoons_Read',
  DictionaryCartoons_Edit = 'DictionaryCartoons_Edit',
  DictionaryCartoons_Delete = 'DictionaryCartoons_Delete',
  DictionaryStudios_Read = 'DictionaryStudios_Read',
  DictionaryStudios_Edit = 'DictionaryStudios_Edit',
  DictionaryStudios_Delete = 'DictionaryStudios_Delete',
  TrixxUsers_Read = 'TrixxUsers_Read',
  TrixxUsers_Edit = 'TrixxUsers_Edit',
  TrixxRoles_Read = 'TrixxRoles_Read',
  TrixxRoles_Edit = 'TrixxRoles_Edit',
  CartoonsPack_Read = 'CartoonsPack_Read',
  CartoonsPack_Edit = 'CartoonsPack_Edit'
}
