/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Permission } from '../models/permission';
export interface RoleEditModel {
  id?: number | null;
  name?: string | null;
  permissions?: Array<Permission> | null;
}
