/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkscreenPermissionsModel } from '../models/workscreen-permissions-model';
export interface RoleModel {
  name: string;
  permissions: Array<WorkscreenPermissionsModel>;
}
