/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserModel {
  id?: number;
  password?: string | null;
  roles?: Array<number> | null;
}
