/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserManuallyCreateModel {
  roles?: Array<number> | null;
  userName?: string | null;
}
