/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserListItem {
  id: number;
  isLockable?: boolean;
  isLocked?: boolean;
  label?: string | null;
}
