/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SelectItem } from '../models/select-item';
export interface UserModel {
  roles: Array<SelectItem>;
  userName: string;
}
