/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum Workscreen {
  MainPage = '\u0413\u043B\u0430\u0432\u043D\u0430\u044F',
  DictionaryCartoons = '\u041C\u0443\u043B\u044C\u0442\u0444\u0438\u043B\u044C\u043C\u044B',
  DictionaryStudios = '\u041C\u0443\u043B\u044C\u0442. \u0421\u0442\u0443\u0434\u0438\u0438',
  TrixxUsers = '\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0438',
  TrixxRoles = '\u0420\u043E\u043B\u0438',
  CartoonsPack = '\u041F\u0430\u043A\u0438'
}
