/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum Workscreen {
  MainPage = 'MainPage',
  DictionaryCartoons = 'DictionaryCartoons',
  DictionaryStudios = 'DictionaryStudios',
  TrixxUsers = 'TrixxUsers',
  TrixxRoles = 'TrixxRoles'
}
