/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PermissionModel } from '../models/permission-model';
import { Workscreen } from '../models/workscreen';
export interface WorkscreenPermissionsModel {
  permissions: Array<PermissionModel>;
  workscreen: Workscreen;
}
