/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleListItem } from '../../models/role-list-item';

export interface ApiRolesRolesGet$Params {
}

export function apiRolesRolesGet(http: HttpClient, rootUrl: string, params?: ApiRolesRolesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleListItem>>> {
  const rb = new RequestBuilder(rootUrl, apiRolesRolesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoleListItem>>;
    })
  );
}

apiRolesRolesGet.PATH = '/api/Roles/roles';
