name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Angular dependencies
      run: |
        cd TrixxDiscordBot/trixxdiscordbot.client
        npm install

    - name: Build Angular
      run: |
        cd TrixxDiscordBot/trixxdiscordbot.client
        npm run build

    - name: Build .NET backend
      run: |
        cd TrixxDiscordBot/TrixxDiscordBot.Server
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o publish

    - name: Copy frontend
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.TRIXX_SERVER_HOST }}
        username: ${{ secrets.TRIXX_SERVER_USER }}
        key: ${{ secrets.TRIXX_SERVER_SSH_KEY }}
        source: "trixxdiscordbot.client/dist/*"
        target: "/var/www/v2trixx/client/"

    - name: Copy backend
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.TRIXX_SERVER_HOST }}
        username: ${{ secrets.TRIXX_SERVER_USER }}
        key: ${{ secrets.TRIXX_SERVER_SSH_KEY }}
        source: "TrixxDiscordBot.Server/publish/*"
        target: "/var/www/v2trixx/server/"
        
    - name: Restart service
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.TRIXX_SERVER_HOST }}
        username: ${{ secrets.TRIXX_SERVER_USER }}
        key: ${{ secrets.TRIXX_SERVER_SSH_KEY }}
        script: |
          sudo systemctl restart trixxdiscordbot